name: NotzWarps
version: '2.1.3'
main: dev.kaato.notzwarps.NotzWarp
softdepend: [ NotzAPI ]
api-version: '1.13'
authors: [ KaaDev ]
description: Warp and TPA plugin with a fully customizable integrated GUI for warps with auto-sort.
website: https://kaato.dev

commands:
  warp:
    description: error in warp command
    usage: /warp
    aliases:
      - w
      - wp
      - ws
      - wps
      - warps
      - spawn
      - spawnvip
  nwarp:
    description: error in nwarp command
    usage: /nwarp
    aliases:
      - nw
      - nwp
      - nws
      - nwps
      - nwarps
  tpa:
    description: error in tpa
    usage: /tpa
    aliases:
      - tpaccept
      - tpaceitar
      - tpacancel
      - tpadeny
      - tparefuse
      - tpacancelar
      - tparecusar

permissions:
  notzwarps.admin:
    description: perm admin
    default: false
  notzwarps.nodelay:
    description: perm no delay
    default: false
  notzwarps.vip:
    description: perm vip
    default: false