name: NotzWarps
version: '2.1.1'
author: https://kaato.dev
main: dev.kaato.notzwarps.Main
#api-version: '1.18'

commands:
  warp:
    description: error in warp command
    usage: /warp
    aliases:
      - w
      - wp
      - ws
      - wps
      - warps
      - spawn
      - spawnvip
  nwarp:
    description: error in nwarp command
    usage: /nwarp
    aliases:
      - nw
      - nwp
      - nws
      - nwps
      - nwarps
  tpa:
    description: error in tpa
    usage: /tpa
    aliases:
      - tpaccept
      - tpaceitar
      - tpacancel
      - tpadeny
      - tparefuse
      - tpacancelar
      - tparecusar

permissions:
  notzwarps.admin:
    description: perm admin
    default: false
  notzwarps.nodelay:
    description: perm no delay
    default: false
  notzwarps.vip:
    description: perm vip
    default: false